import { createElement as h } from "react";
import type { FormDefinition } from "./form-config";

export interface PdfPatient {
  patient_id: string;
  patient_name: string;
  status: string;
  created_at: string;
  updated_at: string;
  form_json: Record<string, string>;
}

export interface PdfHeader {
  doctorName: string;
  hospitalName: string;
}

function formatDate(value: string) {
  try {
    return new Date(value).toLocaleString();
  } catch {
    return value;
  }
}

async function renderDocument(
  patient: PdfPatient,
  definition: FormDefinition,
  header: PdfHeader,
): Promise<Blob> {
  const { Document, Page, Text, View, StyleSheet, pdf } = await import("@react-pdf/renderer");

  const styles = StyleSheet.create({
    page: { padding: 36, fontSize: 10, color: "#1f2937", fontFamily: "Helvetica" },
    bar: { backgroundColor: "#1e5fbf", padding: 14, borderRadius: 6, marginBottom: 16 },
    hospital: { color: "#ffffff", fontSize: 15, fontFamily: "Helvetica-Bold" },
    doctor: { color: "#dbeafe", fontSize: 9, marginTop: 3 },
    formTitle: { color: "#ffffff", fontSize: 10, marginTop: 6 },
    metaRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 14 },
    meta: { fontSize: 9, color: "#4b5563" },
    section: { marginBottom: 12, borderBottom: "1 solid #e5e7eb", paddingBottom: 8 },
    sectionTitle: {
      fontSize: 11,
      fontFamily: "Helvetica-Bold",
      color: "#1e5fbf",
      marginBottom: 6,
    },
    row: { flexDirection: "row", marginBottom: 3 },
    label: { width: "35%", color: "#6b7280" },
    value: { width: "65%" },
    signature: { marginTop: 28, alignItems: "flex-end" },
    signLine: { borderTop: "1 solid #9ca3af", width: 160, paddingTop: 4, textAlign: "center" },
    footer: { marginTop: 18, fontSize: 8, color: "#9ca3af", textAlign: "center" },
  });

  const doc = h(
    Document,
    { title: `${patient.patient_id} — ${definition.label}` },
    h(
      Page,
      { size: "A4", style: styles.page },
      h(
        View,
        { style: styles.bar },
        h(Text, { style: styles.hospital }, header.hospitalName || "MedForms Pro"),
        h(Text, { style: styles.doctor }, `Dr. ${header.doctorName || "—"}`),
        h(Text, { style: styles.formTitle }, definition.label),
      ),
      h(
        View,
        { style: styles.metaRow },
        h(Text, { style: styles.meta }, `Patient ID: ${patient.patient_id}`),
        h(Text, { style: styles.meta }, `Status: ${patient.status}`),
        h(Text, { style: styles.meta }, `Created: ${formatDate(patient.created_at)}`),
      ),
      ...definition.sections.map((section) =>
        h(
          View,
          { key: section.key, style: styles.section, wrap: false },
          h(Text, { style: styles.sectionTitle }, section.title),
          ...section.fields.map((field) =>
            h(
              View,
              { key: field.name, style: styles.row },
              h(Text, { style: styles.label }, field.label),
              h(Text, { style: styles.value }, patient.form_json[field.name] || "—"),
            ),
          ),
        ),
      ),
      h(
        View,
        { style: styles.signature },
        h(Text, { style: styles.signLine }, `Dr. ${header.doctorName || "—"}`),
      ),
      h(
        Text,
        { style: styles.footer },
        `Generated by MedForms Pro on ${new Date().toLocaleString()} — confidential medical record`,
      ),
    ),
  );

  return pdf(doc as never).toBlob();
}

export function pdfFileName(patient: PdfPatient, definition: FormDefinition) {
  const name = (patient.patient_name || "patient").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  return `${patient.patient_id}-${definition.type}-${name}.pdf`;
}

export async function downloadPatientPdf(
  patient: PdfPatient,
  definition: FormDefinition,
  header: PdfHeader,
) {
  const [blob, { saveAs }] = await Promise.all([
    renderDocument(patient, definition, header),
    import("file-saver"),
  ]);
  saveAs(blob, pdfFileName(patient, definition));
}

export async function downloadPatientsZip(
  patients: PdfPatient[],
  definition: FormDefinition,
  header: PdfHeader,
) {
  const [{ default: JSZip }, { saveAs }] = await Promise.all([
    import("jszip"),
    import("file-saver"),
  ]);
  const zip = new JSZip();
  for (const patient of patients) {
    const blob = await renderDocument(patient, definition, header);
    zip.file(pdfFileName(patient, definition), blob);
  }
  const archive = await zip.generateAsync({ type: "blob" });
  saveAs(archive, `medforms-${definition.type}-${patients.length}-records.zip`);
}
