/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFormsTypeIndexRouteImport } from './routes/_authenticated/forms.$type.index'
import { Route as AuthenticatedFormsTypePatientIdRouteImport } from './routes/_authenticated/forms.$type.$patientId'
import { Route as AuthenticatedFormsTypeNewRouteImport } from './routes/_authenticated/forms.$type.new'
import { Route as AuthenticatedFormsTypeEditPatientIdRouteImport } from './routes/_authenticated/forms.$type.edit.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsTypeIndexRoute =
  AuthenticatedFormsTypeIndexRouteImport.update({
    id: '/forms/$type/',
    path: '/forms/$type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsTypePatientIdRoute =
  AuthenticatedFormsTypePatientIdRouteImport.update({
    id: '/forms/$type/$patientId',
    path: '/forms/$type/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsTypeNewRoute =
  AuthenticatedFormsTypeNewRouteImport.update({
    id: '/forms/$type/new',
    path: '/forms/$type/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsTypeEditPatientIdRoute =
  AuthenticatedFormsTypeEditPatientIdRouteImport.update({
    id: '/forms/$type/edit/$patientId',
    path: '/forms/$type/edit/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/forms/$type/$patientId': typeof AuthenticatedFormsTypePatientIdRoute
  '/forms/$type/new': typeof AuthenticatedFormsTypeNewRoute
  '/forms/$type/': typeof AuthenticatedFormsTypeIndexRoute
  '/forms/$type/edit/$patientId': typeof AuthenticatedFormsTypeEditPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/forms/$type/$patientId': typeof AuthenticatedFormsTypePatientIdRoute
  '/forms/$type/new': typeof AuthenticatedFormsTypeNewRoute
  '/forms/$type': typeof AuthenticatedFormsTypeIndexRoute
  '/forms/$type/edit/$patientId': typeof AuthenticatedFormsTypeEditPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/forms/$type/$patientId': typeof AuthenticatedFormsTypePatientIdRoute
  '/_authenticated/forms/$type/new': typeof AuthenticatedFormsTypeNewRoute
  '/_authenticated/forms/$type/': typeof AuthenticatedFormsTypeIndexRoute
  '/_authenticated/forms/$type/edit/$patientId': typeof AuthenticatedFormsTypeEditPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/forms/$type/$patientId'
    | '/forms/$type/new'
    | '/forms/$type/'
    | '/forms/$type/edit/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/forms/$type/$patientId'
    | '/forms/$type/new'
    | '/forms/$type'
    | '/forms/$type/edit/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/forms/$type/$patientId'
    | '/_authenticated/forms/$type/new'
    | '/_authenticated/forms/$type/'
    | '/_authenticated/forms/$type/edit/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$type/': {
      id: '/_authenticated/forms/$type/'
      path: '/forms/$type'
      fullPath: '/forms/$type/'
      preLoaderRoute: typeof AuthenticatedFormsTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$type/$patientId': {
      id: '/_authenticated/forms/$type/$patientId'
      path: '/forms/$type/$patientId'
      fullPath: '/forms/$type/$patientId'
      preLoaderRoute: typeof AuthenticatedFormsTypePatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$type/new': {
      id: '/_authenticated/forms/$type/new'
      path: '/forms/$type/new'
      fullPath: '/forms/$type/new'
      preLoaderRoute: typeof AuthenticatedFormsTypeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$type/edit/$patientId': {
      id: '/_authenticated/forms/$type/edit/$patientId'
      path: '/forms/$type/edit/$patientId'
      fullPath: '/forms/$type/edit/$patientId'
      preLoaderRoute: typeof AuthenticatedFormsTypeEditPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedFormsTypePatientIdRoute: typeof AuthenticatedFormsTypePatientIdRoute
  AuthenticatedFormsTypeNewRoute: typeof AuthenticatedFormsTypeNewRoute
  AuthenticatedFormsTypeIndexRoute: typeof AuthenticatedFormsTypeIndexRoute
  AuthenticatedFormsTypeEditPatientIdRoute: typeof AuthenticatedFormsTypeEditPatientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedFormsTypePatientIdRoute: AuthenticatedFormsTypePatientIdRoute,
  AuthenticatedFormsTypeNewRoute: AuthenticatedFormsTypeNewRoute,
  AuthenticatedFormsTypeIndexRoute: AuthenticatedFormsTypeIndexRoute,
  AuthenticatedFormsTypeEditPatientIdRoute:
    AuthenticatedFormsTypeEditPatientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
